In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("/100_Days_of_ml/Hybrid_Movie_Recommendation_System/data/final_movies.csv")

In [3]:
movies.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."


In [4]:
movies.shape

(4800, 3)

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      4800 non-null   int64 
 1   title   4800 non-null   object
 2   tags    4800 non-null   object
dtypes: int64(1), object(2)
memory usage: 112.6+ KB


# Content Based Recommendation System

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words="english")

In [7]:
vectors = cv.fit_transform(movies["tags"]).toarray()

In [8]:
vectors.shape

(4800, 5000)

In [9]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4800, 5000))

In [10]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [11]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [12]:
np.count_nonzero(vectors[0])

np.int64(31)

In [13]:
vectors[0][:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0])

## Match Words TO Columns

In [14]:
cv.get_feature_names_out()[:20]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '18thcenturi', '19', '1910', '1920',
       '1930', '1940'], dtype=object)

In [15]:
words = cv.get_feature_names_out()

for i in range(len(words)):
    if vectors[0][i] > 0:
        print(words[i], ":", vectors[0][i])

3d : 1
action : 1
adventur : 1
alien : 2
alienplanet : 1
battl : 1
becom : 1
century : 1
cultureclash : 1
dispatch : 1
fantasi : 1
follow : 1
futur : 1
futurist : 1
jamescameron : 1
marin : 2
mission : 1
moon : 1
order : 1
protect : 1
romanc : 1
sciencefict : 1
sigourneyweav : 1
societi : 1
soldier : 1
space : 1
spacetravel : 1
torn : 1
tribe : 1
uniqu : 1
zoesaldana : 1


In [16]:
vectors[0][:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0])

# Cosine Similarity

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [18]:
similarity[0]

array([1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ], shape=(4800,))

In [20]:
print(similarity[0][0])

0.9999999999999998


In [21]:
similarity[0][1]

np.float64(0.08458258116519013)

In [22]:
movies[movies["title"]=="Avatar"]

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."


In [25]:
print(movies[movies["title"]=="Avatar"].index[0])

0


In [31]:
movie_index = movies[movies["title"]=="Avatar"].index[0]

In [32]:
print(movie_index)

0


In [33]:
similarity[movie_index]

array([1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ], shape=(4800,))

In [34]:
distances = similarity[movie_index]

### Enumerate 

In [28]:
numbers = [10,20,30]
for item in enumerate(numbers):
    print(item)

(0, 10)
(1, 20)
(2, 30)


In [35]:
list(enumerate(distances))

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.08458258116519013)),
 (2, np.float64(0.08718572905786445)),
 (3, np.float64(0.074458079104994)),
 (4, np.float64(0.19184045508446734)),
 (5, np.float64(0.1098436937909367)),
 (6, np.float64(0.04078236951430929)),
 (7, np.float64(0.1487044791289829)),
 (8, np.float64(0.06003002251876642)),
 (9, np.float64(0.09802861627917438)),
 (10, np.float64(0.10397504898200727)),
 (11, np.float64(0.09592022754223367)),
 (12, np.float64(0.09158437663089952)),
 (13, np.float64(0.04559607525875532)),
 (14, np.float64(0.12996881122750908)),
 (15, np.float64(0.06367145399670132)),
 (16, np.float64(0.08000711205939975)),
 (17, np.float64(0.14273829330008253)),
 (18, np.float64(0.09620723036050562)),
 (19, np.float64(0.08419653359482289)),
 (20, np.float64(0.05881716976750462)),
 (21, np.float64(0.11277677488692017)),
 (22, np.float64(0.06711560552140244)),
 (23, np.float64(0.0885807893036239)),
 (24, np.float64(0.05405405405405406)),
 (25, np.float64

In [37]:
movie_list = list(enumerate(distances))
print(movie_list)

[(0, np.float64(0.9999999999999998)), (1, np.float64(0.08458258116519013)), (2, np.float64(0.08718572905786445)), (3, np.float64(0.074458079104994)), (4, np.float64(0.19184045508446734)), (5, np.float64(0.1098436937909367)), (6, np.float64(0.04078236951430929)), (7, np.float64(0.1487044791289829)), (8, np.float64(0.06003002251876642)), (9, np.float64(0.09802861627917438)), (10, np.float64(0.10397504898200727)), (11, np.float64(0.09592022754223367)), (12, np.float64(0.09158437663089952)), (13, np.float64(0.04559607525875532)), (14, np.float64(0.12996881122750908)), (15, np.float64(0.06367145399670132)), (16, np.float64(0.08000711205939975)), (17, np.float64(0.14273829330008253)), (18, np.float64(0.09620723036050562)), (19, np.float64(0.08419653359482289)), (20, np.float64(0.05881716976750462)), (21, np.float64(0.11277677488692017)), (22, np.float64(0.06711560552140244)), (23, np.float64(0.0885807893036239)), (24, np.float64(0.05405405405405406)), (25, np.float64(0.05170108966939356)), (

In [38]:
movie_list[:10]

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.08458258116519013)),
 (2, np.float64(0.08718572905786445)),
 (3, np.float64(0.074458079104994)),
 (4, np.float64(0.19184045508446734)),
 (5, np.float64(0.1098436937909367)),
 (6, np.float64(0.04078236951430929)),
 (7, np.float64(0.1487044791289829)),
 (8, np.float64(0.06003002251876642)),
 (9, np.float64(0.09802861627917438))]

In [39]:
movie_list = sorted(
    movie_list,
    key=lambda x:x[1],
    reverse=True
)

In [40]:
movie_list[:10]

[(0, np.float64(0.9999999999999998)),
 (1213, np.float64(0.29061909685954823)),
 (2403, np.float64(0.2726248784031354)),
 (3723, np.float64(0.26401000024165)),
 (507, np.float64(0.25903973506580724)),
 (539, np.float64(0.2537477434955704)),
 (582, np.float64(0.2484013136974297)),
 (1201, np.float64(0.24784079854830487)),
 (1191, np.float64(0.23995690956687135)),
 (61, np.float64(0.23490461932490855))]

In [41]:
movie_list[1:6] # skip 1st

[(1213, np.float64(0.29061909685954823)),
 (2403, np.float64(0.2726248784031354)),
 (3723, np.float64(0.26401000024165)),
 (507, np.float64(0.25903973506580724)),
 (539, np.float64(0.2537477434955704))]

In [43]:
movies.iloc[movie_index].title

'Avatar'

In [46]:
def recommend(movie):
      
    # Step 1
    movie_index = movies[movies["title"] == movie].index[0]
    
    # Step 2
    distances = similarity[movie_index]

    # Step 3
    movie_list = sorted(
        list(enumerate(distances)),
        key=lambda x: x[1],
        reverse=True
    )
    # Step 4
    recommended_movies = []
    # Step 5
    for i in movie_list[1:6]:
        recommended_movies.append(movies.iloc[i[0]].title)

    return recommended_movies

In [51]:
recommend("Pirates of the Caribbean: At World's End")

["Pirates of the Caribbean: Dead Man's Chest",
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'Pirates of the Caribbean: On Stranger Tides',
 'Life of Pi',
 '20,000 Leagues Under the Sea']

In [52]:
import pickle

In [54]:
pickle.dump(
    movies,
    open("/100_Days_of_ml/Hybrid_Movie_Recommendation_System/models/movies.pkl","wb")
)

In [55]:
pickle.dump(
    similarity,
    open("/100_Days_of_ml/Hybrid_Movie_Recommendation_System/models/similarity.pkl","wb")
)